### ISSUE TITLE
processMessage failed

### ISSUE THREAD

**Issue by cryptocoinserver** [jBenes/angular-imgcache.js#15]
Hello jBenes,
i'm stuck at this error messages since weeks:

```
imgcache.js:44 INFO: LocalFileSystem opened
imgcache.js:44 INFO: Local cache folder opened: file:///storage/emulated/0/imgcache/
imgcache.js:44 INFO: .nomedia file created.
cordova.js:1058 processMessage failed: Error: TypeError: Cannot read property 'resolve' of undefined
cordova.js:1059 processMessage failed: Stack: TypeError: Cannot read property 'resolve' of undefined
    at file:///storage/emulated/0/Android/data/com.intel.html5tools.apppreview/cache/previews/WPIonic/1/lib/angular-imgcache.js:8:31
    at _checkSize (file:///storage/emulated/0/Android/data/com.intel.html5tools.apppreview/cache/previews/WPIonic/1/bower_components/imgcache.js/js/imgcache.js:526:33)
    at file:///storage/emulated/0/Android/data/com.intel.html5tools.apppreview/cache/previews/WPIonic/1/bower_components/imgcache.js/js/imgcache.js:536:5
    at _androidNoMediaFileCreated (file:///storage/emulated/0/Android/data/com.intel.html5tools.apppreview/cache/previews/WPIonic/1/bower_components/imgcache.js/js/imgcache.js:344:45)
    at DirectoryEntry.getFile.win (file:///storage/emulated/0/Android/data/com.intel.html5tools.apppreview/cac…iews/WPIonic/1/plugins/org.apache.cordova.file/www/DirectoryEntry.js:109:9)
    at Object.cordova.callbackFromNative (file:///storage/emulated/0/Android/data/com.intel.html5tools.apppreview/cache/previews/WPIonic/1/cordova.js:292:54)
    at processMessage (file:///storage/emulated/0/Android/data/com.intel.html5tools.apppreview/cache/previews/WPIonic/1/cordova.js:1053:21)
    at Function.androidExec.processMessages (file:///storage/emulated/0/Android/data/com.intel.html5tools.apppreview/cache/previews/WPIonic/1/cordova.js:1090:13)
    at pollOnce (file:///storage/emulated/0/Android/data/com.intel.html5tools.apppreview/cache/previews/WPIonic/1/cordova.js:955:17)
    at pollOnceFromOnlineEvent (file:///storage/emulated/0/Android/data/com.intel.html5tools.apppreview/cache/previews/WPIonic/1/cordova.js:945:5)
cordova.js:1060 processMessage failed: Message: S01 File1568179966 {"fullPath":"\/imgcache\/.nomedia","filesystemName":"persistent","isDirectory":false,"nativeURL":"file:\/\/\/storage\/emulated\/0\/imgcache\/.nomedia","filesystem":1,"isFile":true,"name":".nomedia"}
```

I can't find a solution.
I'm using IntelXDK for development and it's an Ionic-Applicaiton.

Thank you
mysecondworld

**Comment by cryptocoinserver** [comment]
I think that's the origin of the problem:

``` javascript
ImgCache.$deferred.resolve();
```

**Comment by cryptocoinserver** [comment]
OMG I finally solved it! I missed the ImgCache there:
.run(function($ionicPlatform, **ImgCache**) {
